ALTER TABLE products
ADD COLUMN category VARCHAR(255) NOT NULL AFTER name,
ADD COLUMN unit VARCHAR(50) NOT NULL AFTER quantity,
ADD COLUMN expiry DATE NOT NULL AFTER unit,
ADD COLUMN description TEXT AFTER expiry;
